name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up C++ environment
    - name: Set up C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ cmake

    # Step 3: Build the project
    - name: Build the C++ project
      run: |
        g++ -std=c++17 -o my_program main.cpp functions.cpp

    # Step 4: Run the tests (Here, you can adjust this based on your test structure)
    - name: Run tests
      run: |
        ./my_program
